backend:
  name: github
  repo: ваше_имя/pro-lombard-site  # Замените на ваше (username/repo-name)
  branch: main  # Или master, если ваш default branch другой

media_folder: uploads
public_folder: /uploads

collections:
  - name: "texts"
    label: "Тексты"
    files:
      - label: "Русский"
        name: "ru"
        file: "data/ru.json"
        fields:
          - {label: "About Title", name: "about_title", widget: string}
          - {label: "About Text", name: "about_text", widget: text}
          - {label: "Service Gold", name: "service_gold", widget: string}
          - {label: "Service Phones", name: "service_phones", widget: string}
          - {label: "Service Laptops", name: "service_laptops", widget: string}
          - {label: "Conditions", name: "conditions", widget: text}
          - {label: "Branches Title", name: "branches_title", widget: string}
          - {label: "Branches", name: "branches", widget: list, fields: [{label: "Address", name: "address", widget: string}, {label: "Hours", name: "hours", widget: string}, {label: "2GIS Link", name: "gis_link", widget: string}]}
          - {label: "Calculator Title", name: "calculator_title", widget: string}
          - {label: "Proba Label", name: "proba_label", widget: string}
          - {label: "Weight Label", name: "weight_label", widget: string}
          - {label: "Days Label", name: "days_label", widget: string}
          - {label: "Loan Sum", name: "loan_sum", widget: string}
          - {label: "Return Sum", name: "return_sum", widget: string}
          - {label: "Error", name: "error", widget: string}
          - {label: "Rules Title", name: "rules_title", widget: string}
          - {label: "Rules Text", name: "rules_text", widget: text}
          - {label: "Documents", name: "documents", widget: list, fields: [{label: "Name", name: "name", widget: string}, {label: "File", name: "file", widget: string}]}
          - {label: "Contacts Title", name: "contacts_title", widget: string}
          - {label: "Phone", name: "phone", widget: string}
          - {label: "Whatsapp", name: "whatsapp", widget: string}

      - label: "Казахский"
        name: "kz"
        file: "data/kz.json"
        fields:
          - {label: "About Title", name: "about_title", widget: string}
          - {label: "About Text", name: "about_text", widget: text}
          - {label: "Service Gold", name: "service_gold", widget: string}
          - {label: "Service Phones", name: "service_phones", widget: string}
          - {label: "Service Laptops", name: "service_laptops", widget: string}
          - {label: "Conditions", name: "conditions", widget: text}
          - {label: "Branches Title", name: "branches_title", widget: string}
          - {label: "Branches", name: "branches", widget: list, fields: [{label: "Address", name: "address", widget: string}, {label: "Hours", name: "hours", widget: string}, {label: "2GIS Link", name: "gis_link", widget: string}]}
          - {label: "Calculator Title", name: "calculator_title", widget: string}
          - {label: "Proba Label", name: "proba_label", widget: string}
          - {label: "Weight Label", name: "weight_label", widget: string}
          - {label: "Days Label", name: "days_label", widget: string}
          - {label: "Loan Sum", name: "loan_sum", widget: string}
          - {label: "Return Sum", name: "return_sum", widget: string}
          - {label: "Error", name: "error", widget: string}
          - {label: "Rules Title", name: "rules_title", widget: string}
          - {label: "Rules Text", name: "rules_text", widget: text}
          - {label: "Documents", name: "documents", widget: list, fields: [{label: "Name", name: "name", widget: string}, {label: "File", name: "file", widget: string}]}
          - {label: "Contacts Title", name: "contacts_title", widget: string}
          - {label: "Phone", name: "phone", widget: string}
          - {label: "Whatsapp", name: "whatsapp", widget: string}

  - name: "rates"
    label: "Расценки"
    files:
      - file: "data/rates.json"
        label: "Расценки"
        name: "rates"
        fields:
          - {label: "585 пробы (тг/гр)", name: "585", widget: number}
          - {label: "750 пробы (тг/гр)", name: "750", widget: number}
          - {label: "Лом (тг/гр)", name: "lom", widget: number}
          - {label: "Комиссия % в день", name: "percent", widget: number}

  - name: "documents"
    label: "Документы"
    folder: "uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "title", widget: string}
      - {label: "Файл", name: "file", widget: file}
