backend:
  name: auth0
  auth0:
    domain: "ваш-domain.auth0.com"  # Из Auth0
    client_id: "ВАШ_CLIENT_ID"      # Из Auth0
    client_secret: "ВАШ_CLIENT_SECRET"  # Из Auth0
    audience: "https://api.example.com"  # Опционально, если есть API в Auth0
    scope: "openid profile email"   # Стандартные scopes для логина

# Остальная часть без изменений: media_folder, collections и т.д.
media_folder: uploads
public_folder: /uploads

collections:
  - name: "texts"
    label: "Тексты"
    files:
      - label: "Русский"
        name: "ru"
        file: "data/ru.json"
        fields:
          - {label: "About Title", name: "about_title", widget: string}
          # ... Все поля, как в предыдущем сообщении

      - label: "Казахский"
        name: "kz"
        file: "data/kz.json"
        fields:
          - {label: "About Title", name: "about_title", widget: string}
          # ... Все поля

  - name: "rates"
    label: "Расценки"
    files:
      - file: "data/rates.json"
        label: "Расценки"
        name: "rates"
        fields:
          - {label: "585 пробы (тг/гр)", name: "585", widget: number}
          # ... Остальные

  - name: "documents"
    label: "Документы"
    folder: "uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "title", widget: string}
      - {label: "Файл", name: "file", widget: file}
